

import 'package:audioplayers/audioplayers.dart';
import 'package:azkary/business_layer/cubit/allquraancubit.dart';
import 'package:azkary/business_layer/states/quraan_state.dart';
import 'package:azkary/data_layer/aya_of_day/api_aya.dart';
import 'package:azkary/quraan_api.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class AllSur extends StatelessWidget {
  AllSur(
      {Key? key,
      required this.inte,
      required this.sur,
      required this.audioPlayer})
      : super(key: key);

  List<Surahs> sur;
  List<Qari>? qari;
  AudioPlayer audioPlayer;

  //String? audiopath;
  int inte;
  Duration duration = new Duration();
  Duration position = new Duration();

  //String path = "https://cdn.islamic.network/quran/audio/64/ar.alafasy/7.mp3";
  bool isplaying = false;
  bool isloop = false;
  List<IconData> icons = [
    Icons.play_circle_fill,
    Icons.pause_circle_filled,
  ];

//List<Ayahs  > sura;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<QuraanCubit, QuraanState>(builder: (context, state) {
      if (state is AllQuraanState) {
        var cubit = BlocProvider.of<QuraanCubit>(context).getAllQuraan();

        sur = (state).allquraanlist!;
        return Directionality(
          textDirection: TextDirection.rtl,
          child: Scaffold(
            // Container(


            appBar: AppBar(
             // leadingWidth: tr,
              backgroundColor: Colors.white.withOpacity(.2),
              title:                 Container(
                  alignment: Alignment.topCenter,
                  width: double.infinity,
                  height: 80,
                  decoration: BoxDecoration(
                    // color: Colors.brown.withOpacity(.7),

                      image: DecorationImage(
                          fit: BoxFit.fill,
                          image:AssetImage('images/surah.jpeg',)
                      )
                  ),
                  child: Center(
                      child: Text(
                        sur[inte].name.toString(),
                        style: TextStyle(
                          fontSize: 28,
                          color: Colors.black,
                        ),
                      ))),
              leadingWidth: 0,



              //  backgroundColor:  Color(0xFFE77471		).withOpacity(.3),
              elevation: 0,
            ),
            body:
          


            Padding(
              padding: const EdgeInsets.all(10),
              child: Container(
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(30),
                  color: Colors.greenAccent.withOpacity(.1)
                ),
                child: ListView.builder(
                          scrollDirection: Axis.vertical,
                          itemCount:
                          1,
                          //sur.length,
                          // sur![inte].ayahs?.length,
                          itemBuilder: (context, index) =>
                              Expanded(
                                //  padding: const EdgeInsets.all(20.0),
                                  child: GestureDetector(
                                    onTap: () {
                                      // this.audioPlayer.play(sur[index].ayahs![index]?.audio);
                                      // ;
                                      //  Navigator.push(context, MaterialPageRoute(builder: (context)=>Audio(qari:sur)));
                                    },

                                    //  color: Color(0xFF99BADD),


                                      child: RichText(
                                        // textAlign: cubit.autogenerated.data.surahs[numberSurahs].ayahs[numberSurahs].number<=20?TextAlign.center:TextAlign.justify,
                                        text: TextSpan(
                                          children: [
                                            for(int i =0;i<sur[inte].ayahs!.length;i++,)...{
                                              TextSpan(
                                                text:''+sur[inte].ayahs![i].text.toString()+'',
                                                style:  TextStyle(
                                                  color: Colors.black,
                                                  fontSize: 29,
                                                  //fontFamily: 'UthmanicHafs',
                                                  fontWeight:FontWeight.w500 ,
                                                ),
                                              ),
                                              TextSpan(
                                                  text:'《${sur[inte].ayahs![i].numberInSurah.toString()}》',
                                                  style: TextStyle(
                                                    fontSize: 22,
                                                    // fontWeight: FontWeight.w400,
                                                    color: Colors.brown,
                                                  )
                                              ),
                                            }
                                          ],
                                        ),
                                      ),
                                    ),
//
//                             Column(children: [
//                               Row(
//                                 children: [
//                                   Container(
//                                     width: 30,
//                                     height: 50,
//                                     decoration: BoxDecoration(
//                                         image: DecorationImage(
//                                       image: AssetImage('images/rakam.png'),
//                                     )),
//                                     child: Center(
//                                       child: Text(
//                                         sur![inte]
//                                             .ayahs![index]
//                                             .numberInSurah
//                                             .toString(),
//                                         style: TextStyle(
//                                             fontSize: 20,
//                                             color: Colors.black,
//                                             fontWeight: FontWeight.bold),
//                                       ),
//                                     ),
//                                   ),
//                                   Expanded(
//                                     child: Text(
//                                       "" +
//                                           sur![inte]
//                                               .ayahs![index]
//                                               .text
//                                               .toString(),
//                                       style: TextStyle(
//                                           fontSize: 24,
//                                           color: Colors.black,
//                                           fontWeight: FontWeight.bold),
//                                     ),
//                                   ),
//                                 ],
//
// // SizedBox(width: 60,),
//                               ),
//                             ]),
                                    // Card(
                                    //   color: Color(0xFFC68E17).withOpacity(.1),
                                  ))),
              ),
            ),



              



                            // Row(
                            //   children: [
                            //     Text("الجزء" +
                            //         sur![inte].ayahs![index].juz.toString(),style: TextStyle(color: Colors.blueGrey),),
                            //     Spacer(),
                            //     Text("الحزب" +
                            //         sur![inte]
                            //             .ayahs![index]
                            //             .hizbQuarter
                            //             .toString(),style: TextStyle(color: Colors.blueGrey),),
                            //   ],
                            // )
                          


                          // Text(sur![inte].ayahs![index].numberInSurah.toString(),
                          //   style: TextStyle(
                          //       fontSize: 28, color: Colors
                          //       .black),),









          //    SizedBox(height: 20,),
        );
      } else
        return CircularProgressIndicator();
    });
  }
}

//////////////////////////////////////////////////
//      child: RichText(
//                        // textAlign: cubit.autogenerated.data.surahs[numberSurahs].ayahs[numberSurahs].number<=20?TextAlign.center:TextAlign.justify,
//                         text: TextSpan(
//                           children: [
//                             for(int i =0;i<cubit.autogenerated.data.surahs[widget.numberSurahs].ayahs.length;i++,)...{
//                               TextSpan(
//                                 text:''+cubit.autogenerated.data.surahs[widget.numberSurahs].ayahs[i].text+'',
//                                 style:  TextStyle(
//                                   color: Colors.white,
//                                   fontSize: cubit.fontSize,
//                                   fontFamily: 'UthmanicHafs',
//                                   fontWeight:FontWeight.w500 ,
//                                 ),
//                               ),
//                               TextSpan(
//                                 text:'《${cubit.autogenerated.data.surahs[widget.numberSurahs].ayahs[i].numberInSurah.toString()}》',
//                                 style: TextStyle(
//                                   fontSize: 22,
//                                   fontWeight: FontWeight.w400,
//                                   color: Colors.amberAccent,
//                                 )
//                               ),
//                             }
//                           ],
//                         ),
//                       ),
/////////////////////////////////////////////////////////
// Column(
// children: [
// Row(
// children: [
// Expanded(
// child: Text(
// "" + sur![inte].ayahs![index].text.toString(),
// style: TextStyle(
// fontSize: 28,
// color:  Colors.black,
// fontWeight: FontWeight.bold),
// ),
// ),
//
//
// Container(
// width: 30,
// height: 50,
// decoration: BoxDecoration(
// image: DecorationImage(
// image: AssetImage('images/rakam.png'),
// )),
// child: Center(
// child: Text(
// sur![inte]
// .ayahs![index]
// .numberInSurah
//     .toString(),
// style: TextStyle(
// fontSize: 20,
// color: Colors.black,
// fontWeight: FontWeight.bold),
// ),
// ),
// ),
// ],
//
// // SizedBox(width: 60,),
// ),
// ]
// ),
/////////////////////////////////////////////////////////////////////////////////////
// RichText(
// text: TextSpan(
// children: [
// for(int i =0;i<sur[inte].ayahs![index]!.toString();i++,)...{
// TextSpan(
// text:''+sur[i].ayahs![index].text.toString()+'',
// style:  TextStyle(
// color: Colors.black,
//
// // fontSize: cubit.fontSize,
// // fontFamily: 'UthmanicHafs',
// fontWeight:FontWeight.w500 ,
// ),
// ),
// TextSpan(
// text:'《${sur[inte].ayahs![index].numberInSurah.toString()}》',
// style: TextStyle(
// //fontSize: 22,
// // fontWeight: FontWeight.w400,
// color: Colors.amberAccent,
// )
// ),
// }
// ],
// ),
// ),
